### ISSUE TITLE
Clientes não reiniciam quando servidor cai

### ISSUE THREAD

**Issue by lbovolini** [lbovolini/crowd#75]

**Comment by lbovolini** [comment]
```
java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implConnect(UnixAsynchronousSocketChannelImpl.java:301)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.connect(AsynchronousSocketChannelImpl.java:209)
	at com.github.lbovolini.crowd.client.worker.ClientWorker.connect(ClientWorker.java:22)
	at com.github.lbovolini.crowd.client.codebase.CodebaseServiceImpl.onConnect(CodebaseServiceImpl.java:25)
	at com.github.lbovolini.crowd.discovery.request.MulticastClientDispatcher.dispatch(MulticastClientDispatcher.java:34)
	at com.github.lbovolini.crowd.discovery.request.MulticastScheduler.run(MulticastScheduler.java:29)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
